//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string BarcodeNo { get; set; }
        public int ManufacturerId { get; set; }
        public double Price { get; set; }
        public string PurposeOfUsing { get; set; }
        public string SideEffects { get; set; }
    }
}
